var handles = [
  "Faysal_Chowdhury",
  "Xbir",
  "tanvirtasin",
  "Siyam_Talukder",
  "Ether",
  "jubair7",
  "mr_warlock",
  "Reaper08",
  "Miaow",
  "Mahjabin7",
  "Kazi_Irfan",
  "Abir_Hamza",
  "Azhar07",
  "mdNishad_001",
  "HA_BI_BI",
  "tanjill",
  "mahdiuzzamannishat",
  "kingfisher-2",
  "Suzit_Datta",
  "_Berlin_",
  "_kuhaku",
  "Zids",
  "mdnrkn",
  "_Asaduzzaman_",
  "J_A_Jishan",
  "_Tanjid_",
  "mehedi-hasan02",
  "mahir_d_",
  "LONEWOLF09",
  "Tasin_t",
  "mhTipu",
  "falcon83",
  "NILADRI-18",
  "Swajan_",
  "fahadhasan",
  "Meraki_",
  "Al__Ehsan",
  "one_above_all7",
  "Arnobakd",
  "tanvir50198",
  "AR_ratul",
  "OnukromR",
  "Kiyas-Mahmud",
  "Razoana",
  "S0MS0MM1dA",
  "Zero_Tw2",
  "Aursyine_",
];

var organization = "american international university bangladesh";

var scoreToGet = [
  100, 70, 56, 47, 41, 36, 32, 28, 25, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2,
  1, 1,
];
